# Generated by Django 2.2.6 on 2019-10-26 14:43

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custom', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(help_text='+375**-***-**-**', max_length=16, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='Фото профиля')),
                ('country', models.CharField(blank=True, max_length=120, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=80, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=120, null=True, verbose_name='Улица, дом, квартира')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('info', models.TextField(blank=True, max_length=200, null=True, verbose_name='Дополнительна информация')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
